version: '3.7'

services:
  regression:
    image: pytest:latest  # Используем уже созданный образ
    volumes:
      - "D:/Users/Max/PycharmProjects/project_ui_automation:/usr/workspace"  # Примонтируйте текущую директорию в контейнер
      - "./allure-results:/usr/workspace/allure-results"  # Примонтируйте директорию для результатов Allure
    command: /bin/sh -c "pytest -sv --alluredir=allure-results tests/feature_profile_test.py"  # Запускаем конкретный тест
    working_dir: /usr/workspace  # Установите рабочую директорию внутри контейнера
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}

