version: '3.7'

services:
  regression:
    image: pytest:latest
    volumes:
      - workspace:/usr/workspace  # Используем именованный volume для монтирования папки
      - ./allure-results:/usr/workspace/allure-results  # Монтируем директорию для результатов Allure
    command: /bin/sh -c "pytest -sv --alluredir=allure-results tests/feature_profile_test.py"
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}

volumes:
  workspace:
